============================= test session starts =============================
platform win32 -- Python 3.8.2, pytest-3.6.2, py-1.5.3, pluggy-0.6.0 -- C:\Users\marce\anaconda3\envs\codenation\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\marce\codenation\python-7, inifile:
collecting ... collected 2 items

test_main.py::test_get_temperature_by_lat_lng[-14.235004--51.92528-62-16] PASSED [ 50%]
test_main.py::test_valid_connection PASSED                               [100%]

------ generated xml file: C:\Users\marce\codenation\python-7\output.xml ------
========================== 2 passed in 1.27 seconds ===========================
